# CORS (dev)
app:
  cors:
    origins:
      - http://localhost:3005
      - http://localhost:8086
  s3:
    bucket: mnema-media
    region: ru-central1
    endpoint: https://storage.yandexcloud.net
    pathStyleAccess: false
    accessKey: ${AWS_ACCESS_KEY_ID}
    secretKey: ${AWS_SECRET_ACCESS_KEY}
