services:
  postgres:
    networks: [ mnema_net ]
    image: postgres:18
    env_file: [ .env ]
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports: [ "${POSTGRES_PORT}:5432" ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    networks: [ mnema_net ]
    image: redis:7-alpine
    command: [ "redis-server", "--save", "", "--appendonly", "no" ]
    ports: [ "6379:6379" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10

  auth:
    networks: [ mnema_net ]
    #    dns:
    #      - 1.1.1.1
    #      - 8.8.8.8
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: auth-runtime
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_FLYWAY_ENABLED: "true"
      AUTH_ISSUER: http://auth:8080
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GITHUB_CLIENT_ID: ${GH_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GH_CLIENT_SECRET}
      YANDEX_CLIENT_ID: ${YANDEX_CLIENT_ID}
      YANDEX_CLIENT_SECRET: ${YANDEX_CLIENT_SECRET}
    depends_on:
      postgres: { condition: service_healthy }
      redis: { condition: service_healthy }
    ports: [ "8083:8080" ]

  user:
    networks: [ mnema_net ]
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: user-runtime
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME:-${POSTGRES_USER}}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:-${POSTGRES_PASSWORD}}
      SPRING_FLYWAY_ENABLED: "true"
      AUTH_ISSUER_URI: http://auth:8080
      CORE_BASE_URL: http://core:8080/api/core
      MEDIA_BASE_URL: http://media:8080/api/media
      MEDIA_INTERNAL_TOKEN: ${MEDIA_INTERNAL_TOKEN}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      postgres: { condition: service_healthy }
      redis: { condition: service_healthy }
    ports: [ "8084:8080" ]

  core:
    networks: [ mnema_net ]
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: core-runtime
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME:-${POSTGRES_USER}}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:-${POSTGRES_PASSWORD}}
      SPRING_FLYWAY_ENABLED: "true"
      AUTH_ISSUER_URI: http://auth:8080
      MEDIA_BASE_URL: http://media:8080/api/media
      MEDIA_INTERNAL_TOKEN: ${MEDIA_INTERNAL_TOKEN}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      postgres: { condition: service_healthy }
    ports: [ "8085:8080" ]

  media:
    networks: [ mnema_net ]
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: media-runtime
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME:-${POSTGRES_USER}}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:-${POSTGRES_PASSWORD}}
      SPRING_FLYWAY_ENABLED: "true"
      AUTH_ISSUER_URI: http://auth:8080
      MEDIA_INTERNAL_TOKEN: ${MEDIA_INTERNAL_TOKEN}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      AWS_REGION: ${AWS_REGION}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
      AWS_ENDPOINT: ${AWS_ENDPOINT:-https://storage.yandexcloud.net}
      AWS_PATH_STYLE_ACCESS: ${AWS_PATH_STYLE_ACCESS:-false}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports: [ "8086:8080" ]

  import:
    networks: [ mnema_net ]
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: import-runtime
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME:-${POSTGRES_USER}}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:-${POSTGRES_PASSWORD}}
      SPRING_FLYWAY_ENABLED: "true"
      AUTH_ISSUER_URI: http://auth:8080
      CORE_BASE_URL: http://core:8080/api/core
      MEDIA_BASE_URL: http://media:8080/api/media
      MEDIA_INTERNAL_TOKEN: ${MEDIA_INTERNAL_TOKEN}
    depends_on:
      postgres:
        condition: service_healthy
    ports: [ "8087:8080" ]

  ai:
    networks: [ mnema_net ]
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: ai-runtime
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME:-${POSTGRES_USER}}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:-${POSTGRES_PASSWORD}}
      SPRING_FLYWAY_ENABLED: "true"
      AUTH_ISSUER_URI: http://auth:8080
      CORE_BASE_URL: http://core:8080/api/core
      MEDIA_BASE_URL: http://media:8080/api/media
      MEDIA_INTERNAL_TOKEN: ${MEDIA_INTERNAL_TOKEN}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      APP_AI_VAULT_MASTER_KEY: ${AI_VAULT_MASTER_KEY}
      APP_AI_VAULT_KEY_ID: ${AI_VAULT_KEY_ID}
    depends_on:
      postgres: { condition: service_healthy }
      redis: { condition: service_healthy }
    ports: [ "8088:8080" ]


  frontend:
    networks: [ mnema_net ]
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports: [ "3005:80" ]
    restart: unless-stopped

networks:
  mnema_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.222.0.0/16
