services:
  postgres:
    image: postgres:18
    env_file: [ .env ]
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports: [ "${POSTGRES_PORT}:5432" ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 3s
      retries: 10

  auth:
    dns:
      - 1.1.1.1
      - 8.8.8.8
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: auth-runtime
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_FLYWAY_ENABLED: "true"
      AUTH_ISSUER: http://auth:8080
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GITHUB_CLIENT_ID: ${GH_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GH_CLIENT_SECRET}
      YANDEX_CLIENT_ID: ${YANDEX_CLIENT_ID}
      YANDEX_CLIENT_SECRET: ${YANDEX_CLIENT_SECRET}
    depends_on:
      postgres: { condition: service_healthy }
    ports: [ "8083:8080" ]

  user:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: user-runtime
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME:-${POSTGRES_USER}}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:-${POSTGRES_PASSWORD}}
      SPRING_FLYWAY_ENABLED: "true"
      AUTH_ISSUER_URI: http://auth:8080
    depends_on:
      postgres: { condition: service_healthy }
    ports: [ "8084:8080" ]

  core:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: core-runtime
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME:-${POSTGRES_USER}}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD:-${POSTGRES_PASSWORD}}
      SPRING_FLYWAY_ENABLED: "true"
      AUTH_ISSUER_URI: http://auth:8080
    depends_on:
      postgres: { condition: service_healthy }
    ports: [ "8085:8080" ]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports: [ "3005:80" ]
    restart: unless-stopped

networks:
  default:
    name: mnema-net
