apiVersion: v1
kind: Service
metadata:
  name: mnema-ai-bridge
  namespace: prod
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 32088
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: mnema-ai-bridge-1
  namespace: prod
  labels:
    kubernetes.io/service-name: mnema-ai-bridge
addressType: IPv4
ports:
  - name: http
    protocol: TCP
    port: 32088
endpoints:
  - addresses:
      - 66.248.207.147
