# auth-deploy.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mnema-auth
  namespace: prod
spec:
  replicas: 1
  selector: { matchLabels: { app: mnema-auth } }
  template:
    metadata: { labels: { app: mnema-auth } }
    spec:

      initContainers:
        - name: wait-for-postgres
          image: postgres:18
          command: ['sh','-c','until pg_isready -h postgres.prod.svc.cluster.local -p 5432 -U "$POSTGRES_USER" -d "$POSTGRES_DB"; do echo waiting for postgres; sleep 2; done']
          env:
            - name: POSTGRES_USER
              valueFrom: { secretKeyRef: { name: mnema-secrets, key: POSTGRES_USER } }
            - name: POSTGRES_DB
              valueFrom: { secretKeyRef: { name: mnema-secrets, key: POSTGRES_DB } }

      containers:
        - name: auth
          image: ghcr.io/mattoyuzuru/mnema/auth:latest
          ports: [ { containerPort: 8080 } ]
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres.prod.svc.cluster.local:5432/mnema
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom: { secretKeyRef: { name: mnema-secrets, key: POSTGRES_USER } }
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom: { secretKeyRef: { name: mnema-secrets, key: POSTGRES_PASSWORD } }
            - name: GOOGLE_CLIENT_ID
              valueFrom: { secretKeyRef: { name: mnema-secrets, key: GOOGLE_CLIENT_ID } }
            - name: GOOGLE_CLIENT_SECRET
              valueFrom: { secretKeyRef: { name: mnema-secrets, key: GOOGLE_CLIENT_SECRET } }
            - name: GITHUB_CLIENT_ID
              valueFrom: { secretKeyRef: { name: mnema-secrets, key: GITHUB_CLIENT_ID } }
            - name: GITHUB_CLIENT_SECRET
              valueFrom: { secretKeyRef: { name: mnema-secrets, key: GITHUB_CLIENT_SECRET } }
            - name: YANDEX_CLIENT_ID
              valueFrom: { secretKeyRef: { name: mnema-secrets, key: YANDEX_CLIENT_ID } }
            - name: YANDEX_CLIENT_SECRET
              valueFrom: { secretKeyRef: { name: mnema-secrets, key: YANDEX_CLIENT_SECRET } }
            - name: AUTH_ISSUER
              valueFrom: { secretKeyRef: { name: mnema-secrets, key: AUTH_ISSUER } }
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          startupProbe:
            httpGet: { path: /actuator/health, port: 8080 }
            periodSeconds: 2
            failureThreshold: 30
          readinessProbe:
            httpGet: { path: /actuator/health, port: 8080 }
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /actuator/health, port: 8080 }
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: mnema-auth
  namespace: prod
spec:
  selector: { app: mnema-auth }
  ports:
    - port: 80
      targetPort: 8080
