# auth-ingress.yaml

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mnema-auth
  namespace: prod
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts: [ auth.mnema.app ]
      secretName: auth-mnema-app-tls
  rules:
    - host: auth.mnema.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mnema-auth
                port:
                  number: 80
