# core-deploy.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mnema-core
  namespace: prod
spec:
  replicas: 1
  selector: { matchLabels: { app: mnema-core }}
  template: 
    metadata: { labels: { app: mnema-core }}
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:18
          command: [ 'sh','-c','until pg_isready -h postgres.prod.svc.cluster.local -p 5432 -U "$POSTGRES_USER" -d "$POSTGRES_DB"; do echo waiting for postgres; sleep 2; done' ]
          env:
            - name: POSTGRES_USER
              valueFrom: { secretKeyRef: { name: mnema-secrets, key: POSTGRES_USER } }
            - name: POSTGRES_DB
              valueFrom: { secretKeyRef: { name: mnema-secrets, key: POSTGRES_DB } }
              
      containers:
        - name: core
          image: ghcr.io/mattoyuzuru/mnema/core:latest
          ports: [ { containerPort: 8080 } ]
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres.prod.svc.cluster.local:5432/mnema
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom: { secretKeyRef: { name: mnema-secrets, key: POSTGRES_USER } }
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom: { secretKeyRef: { name: mnema-secrets, key: POSTGRES_PASSWORD } }
            - name: GOOGLE_CLIENT_ID
              valueFrom: { secretKeyRef: { name: mnema-secrets, key: GOOGLE_CLIENT_ID } }
            - name: GOOGLE_CLIENT_SECRET
              valueFrom: { secretKeyRef: { name: mnema-secrets, key: GOOGLE_CLIENT_SECRET } }
            - name: AUTH_ISSUER_URI
              valueFrom: { secretKeyRef: { name: mnema-secrets, key: AUTH_ISSUER_URI } }
            - name: MEDIA_BASE_URL
              value: http://mnema-media/api/media
            - name: MEDIA_INTERNAL_TOKEN
              valueFrom: { secretKeyRef: { name: mnema-secrets, key: MEDIA_INTERNAL_TOKEN } }
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: APP_ENV
              value: prod
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          startupProbe:
            httpGet: { path: /api/core/actuator/health/liveness, port: 8080 }
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 90
          readinessProbe:
            httpGet: { path: /api/core/actuator/health/readiness, port: 8080 }
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
          livenessProbe:
            httpGet: { path: /api/core/actuator/health/liveness, port: 8080 }
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: mnema-core
  namespace: prod
spec:
  selector: { app: mnema-core }
  ports:
    - port: 80
      targetPort: 8080
