apiVersion: apps/v1
kind: Deployment
metadata:
  name: mnema-frontend
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels: { app: mnema-frontend }
  strategy:
    type: RollingUpdate
    rollingUpdate: { maxUnavailable: 0, maxSurge: 1 }
  template:
    metadata:
      labels: { app: mnema-frontend }
    spec:
      containers:
        - name: frontend
          image: ghcr.io/mattoyuzuru/mnema/frontend:sha-PLACEHOLDER # CI заменит
          ports: [ { containerPort: 80 } ]
          readinessProbe:
            httpGet: { path: /, port: 80 }
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /, port: 80 }
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: mnema-frontend
  namespace: prod
spec:
  selector: { app: mnema-frontend }
  ports:
    - port: 80
      targetPort: 80
