apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mnema
  namespace: prod
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts: [ mnema.app ]
      secretName: mnema-app-tls
  rules:
    - host: mnema.app
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: { name: mnema-frontend, port: { number: 80 } }
          - path: /api/auth
            pathType: Prefix
            backend:
              service: { name: mnema-auth, port: { number: 80 } }
          - path: /api/user
            pathType: Prefix
            backend:
              service: { name: mnema-user, port: { number: 80 } }

