spring:
  profiles:
    active: dev

server:
  servlet:
    context-path: /api/core

# CORS (dev)
app:
  cors:
    origins:
      - http://localhost:3005
      - http://localhost:8084

springdoc:
  swagger-ui:
    oauth:
      client-id: swagger-ui
      client-secret: secret
      use-pkce-with-authorization-code-grant: true
