# CORS (dev)
app:
  cors:
    origins:
      - http://localhost:3005
      - http://localhost:8087
  core:
    base-url: http://localhost:8085/api/core
  media:
    base-url: http://localhost:8086/api/media
