app:
  auth:
    features:
      federated-enabled: false
      require-email-verification: false
  cors:
    origins:
      - http://localhost:3005
      - http://127.0.0.1:3005

auth:
  logout:
    default-redirect: http://localhost:3005/

turnstile:
  site-key: ""
  secret-key: ""
