auth:
  issuer: http://localhost:8083

management:
  endpoints.web.exposure.include: health,info,prometheus

server:
  forward-headers-strategy: native

logging.level.org.springframework.security: DEBUG

# CORS (dev)
app:
  cors:
    origins:
      - http://localhost:3005
      - http://localhost:8084
