apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mnema
  namespace: mnema
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
spec:
  ingressClassName: traefik
  rules:
    - host: mnema.app
      http:
        paths:
          - path: /svc1
            pathType: Prefix
            backend:
              service:
                name: svc1
                port:
                  number: 80
          - path: /svc2
            pathType: Prefix
            backend:
              service:
                name: svc2
                port:
                  number: 80
