apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ai-mnema-app-tls
  namespace: prod
spec:
  secretName: ai-mnema-app-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsNames:
    - ai.mnema.app
