name: Build & Deploy (test)
on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_SVC1: ghcr.io/mattoyuzuru/mnema/svc1
  IMAGE_SVC2: ghcr.io/mattoyuzuru/mnema/svc2
  GIT_SHA: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push svc1
        uses: docker/build-push-action@v6
        with:
          context: ./backend/services/service1
          push: true
          tags: |
            ${{ env.IMAGE_SVC1 }}:${{ env.GIT_SHA }}
            ${{ env.IMAGE_SVC1 }}:latest

      - name: Build & push svc2
        uses: docker/build-push-action@v6
        with:
          context: ./backend/services/service2
          push: true
          tags: |
            ${{ env.IMAGE_SVC2 }}:${{ env.GIT_SHA }}
            ${{ env.IMAGE_SVC2 }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - uses: actions/checkout@v4

      - name: Prepare kubeconfig from secret
        env:
          KUBECONFIG_B64: ${{ secrets.KUBECONFIG_B64 }}
        run: |
          echo "$KUBECONFIG_B64" | base64 -d > kubeconfig

      - name: Inject image tags
        env:
          GIT_SHA: ${{ github.sha }}
        run: |
          find infra/k8s/base -type f -name "*.yaml" -print0 \
            | xargs -0 sed -i "s|{{GIT_SHA}}|$GIT_SHA|g"

      - name: Apply manifests
        run: |
          KUBECONFIG=$PWD/kubeconfig kubectl apply -f infra/k8s/base
